# ==========================================
# CONFIGURACIÓN DE APLICACIÓN
# ==========================================
spring.application.name=Auto_TEC
server.port=8080

# ==========================================
# BASE DE DATOS (POSTGRESQL - RENDER)
# ==========================================
# URL EXTERNA (Para conexión desde tu PC hacia Render)
spring.datasource.url=jdbc:postgresql://dpg-d8fiqvn40ujc73dsq9b0-a.oregon-postgres.render.com:5432/stellantis_db_0rxi?sslmode=require
spring.datasource.username=stellantis_db_0rxi_user
spring.datasource.password=eAuz4Fk2AKY2SiQI0QdVFqoc4It9YHXV
spring.datasource.driverClassName=org.postgresql.Driver

# HIBERNATE / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ==========================================
# THYMELEAF (VISTAS)
# ==========================================
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# ==========================================
# SEGURIDAD Y JWT
# ==========================================
jwt.secret=UsIpuXd1FqMS3Nduu5WbiMrOq8qdZQAr
jwt.expiration=86400000

# ==========================================
# CLOUDINARY (ASSETS)
# ==========================================
cloudinary.cloud_name=dodwyz4zc
cloudinary.api_key=287328935187812
cloudinary.api_secret=o-ZzL8b9wSx4Ssquao1MQXPRI1M

# ==========================================
# LOGGING (DEBUGGING DE ERRORES)
# ==========================================
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.thymeleaf=TRACE

# ==========================================
# GESTIÓN (ACTUATOR)
# ==========================================
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always