spring.application.name=Auto_TEC

# Configuración para H2 (Base de datos en memoria para desarrollo)
spring.datasource.url=jdbc:h2:mem:autotecdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Habilitar consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración del servidor
server.port=8080

#configuraciones
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML5
spring.thymeleaf.encoding=UTF-8

# Configuración de logging
logging.level.org.hibernate.SQL=DEBUG
spring.thymeleaf.cache=false
logging.level.com.organization.Auto_TEC.Service.CustomUserDetailsService=DEBUG
logging.level.com.organization.Auto_TEC.Config=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security.web=DEBUG       